version: '3.8'
services:
  db:
    image: postgres:16
    container_name: banking-db
    restart: always
    environment:
      POSTGRES_USER: recep
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: banking
    ports:
      - "5436:5432"